services:
  db:
    image: postgres:17.0-alpine3.20
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: backend
    expose:
      - 9000
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - db

volumes:
  db: