services:
  db:
    image: postgres:17.0-alpine3.20
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: